language: java
jdk:
  - openjdk8
services:
  - docker
matrix:
  fast_finish: true

env:
  global:
    # DOCKER_USER
    - secure: "CSGFK5aUEWE6g/jSUlqbCSjrYl92Aba9Apmpp47XPSt5+m5sa0/RjnbXO73Za/dElonnrFZc0F6yEo8iqFjjxPz9ZgZD2YHfFWTLubIOvgV2wnN55I6kBUWNT1bqejerrogMSS4x266mufljSaWNWb9Equ4yPP7SlGHH7dpkM9brnNrFxgCK/iwaIECKTCNnxRFKVBHkgdoMtC6D+FOT4VvNKvc6poMdASIC2tPWhDQebmOkGR+rxPLAx8/g3Ck9bauJJ3CMLdTCIKvv8IetzCjwDDk3WwS/hEl0AYdJdLUH+aaTWKX8fgDaXhP9kRh9g24kBi7qWyfuFHFHeiJlqLKuNnVKJiV+GrWUfwfLA6AQG7qHU9Oo+NLmyXgnImgC8r67EuoYMnmSqfFg33Ay33943Qyy3K+6FlrFKpsmvF+aJQwelPsGq+A87ORff5+1+t3Rx3NZDwsRIwtjGxppZhuLrq0KuMvwMC/jYd4mvPEX9/XG4ni76MynrbIYKuzjpFyUwa0nrZw4ln6ReJ3kKkHu4DuFqiuF9RtsfEX7WOGUkYpUjPE9mnRPqfW7TKR5ICmg245X/h0RS7aoqnz8Yy1ZMjFqbhuqj3Fjv2lGxZ11H0KWmb1lxuUSnLKxK2xZsFimERAYO8QVRT6giPfojMiprm4KGT3yDMHiJMUs1JI="
    # DOCKER_PASSWORD
    - secure: "5Y//rIxRgj5ZrC+OXSarxnr5ienUN1wKIACDpg8lfjMdh5Cydh6jFivY0ZeM/VFiIJKrwiSKrJeaT0/aPtwnSs7RJ2P9n/XOLIAzrS+9ryHf/SFPv6ZarMuSSkK/Tibs9dSB5QDAN9yzzLU8VUbJV/l+VYq/V+GH7Poe9qCT3nJVKAjlQIKQuHpEm5f1pG9+6uFAdXRo7Jd/sEd5EdZyfz1X27E/ragn7MHuy3GF5/zT6Ohw2xcqFSPtq4HBkaCLJ6oi2dSM2wBBvG26ziniKSavbVc/WLN1F9yggorZ66XLI/E96C9L4Dt5+8u5JwXWhOQhZ/kBVCPLNQKXrMUft6tRA5DEskZCiV3h6R73N29gDU0O5v+wv+xHW/2uynXM2Dm2N9inXagZ/m679VPXymmSJsFGsaC+DbnuCqrmvwqXHagfPOXMcF1/cisPqfHzXm5eCVh42pLvKdOHIoJauXHFvz2H3xPWNLHrwdkGrznGvvdhiEqpsQfzaXtuHReHD3+iotlsNmtAtdwI9opPMuHpeh8Jbe5mj2sz8hozs+zpDayqTq7zPEMQxBk2WyCDxUJcwBBTuGPKFOoaTg98z8p9PDcLqzx/umnxxcT5uwl701PgQAT3v1WcN78Cs3iUAUctEuLl/lqXLeZmhCcxeAWYf5amLn7AoeYfkgBHcKc="
    - IMAGE_NAME=joachimprinzbach/kloud-assistant

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=$(if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$BRANCH-$COMMIT"; fi | sed 's/\//-/')
  - docker build . -t $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker tag $IMAGE_NAME:latest $IMAGE_NAME:master; fi
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker push $IMAGE_NAME:master; fi
  - docker push $IMAGE_NAME:$TAG

cache:
  directories:
    - '$HOME/.m2/repository'